Update email.yml

diff --git a/.github/workflows/email.yml b/.github/workflows/email.yml
--- a/.github/workflows/email.yml
+++ b/.github/workflows/email.yml
@@ -1,4 +1,4 @@
-name: Docker Image CI
+name: Email and docker
 
 on:
   push:
@@ -12,67 +12,69 @@ jobs:
   build1:
     runs-on: ubuntu-latest
     outputs:
-      exitCode: ${{ steps.set-exit-code.outputs.exitCode }}
+      exitCodeBuild1: ${{ steps.set-exit-code1.outputs.exitCode }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set default exit code
-        id: set-exit-code
-        run: echo "exitCode=0" >>$GITHUB_ENV
+      - name: Set default exit code for build1
+        id: set-exit-code1
+        run: echo "exitCodeBuild1=0" >> $GITHUB_ENV
 
       - name: Build the Docker image
         run: |
           if docker build . --file Dockerfile --tag my-image-name:$(date +%s); then
-            echo "Build successful"
+            echo "Build successful for build1"
           else
-            echo "Build failed"
-            echo "exitCode=1" >>$GITHUB_ENV
+            echo "Build failed for build1"
+            echo "exitCodeBuild1=1" >> $GITHUB_ENV
+            exit 1
           fi
           
-      - name: Send email on failure (chatbotclient)
-        if: ${{ env.exitCode }} != '0'
+      - name: Send email on failure (build1)
+        if: ${{ needs.build1.outputs.exitCodeBuild1 == '1' }}
         uses: dawidd6/action-send-mail@v3
         with:
           server_address: smtp.office365.com
           server_port: 587
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: 'Build Failed: Chatbot Client'
-          body: 'The build for Chatbot Client failed in the GitHub Action workflow.'
+          subject: 'Build Failed: build1'
+          body: 'The build for build1 failed in the GitHub Action workflow.'
           to: 'haritha.guduru@gytworkz.com'
           from: 'santosh.chintapally@gytworkz.com'
 
   build2:
     runs-on: ubuntu-latest
     outputs:
-      exitCode: ${{ steps.set-exit-code.outputs.exitCode }}
+      exitCodeBuild2: ${{ steps.set-exit-code2.outputs.exitCode }}
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Set default exit code
-        id: set-exit-code
-        run: echo "exitCode=0" >>$GITHUB_ENV
+      - name: Set default exit code for build2
+        id: set-exit-code2
+        run: echo "exitCodeBuild2=0" >> $GITHUB_ENV
 
       - name: Build Hello World
         run: |
           if echo Hello, world!; then
-            echo "Build successful"
+            echo "Build successful for build2"
           else
-            echo "Build failed"
-            echo "exitCode=1" >>$GITHUB_ENV
+            echo "Build failed for build2"
+            echo "exitCodeBuild2=1" >> $GITHUB_ENV
+            exit 1
           fi
           
-      - name: Send email on failure (chatbotclient)
-        if: ${{ env.exitCode }} != '0'
+      - name: Send email on failure (build2)
+        if: ${{ needs.build2.outputs.exitCodeBuild2 == '1' }}
         uses: dawidd6/action-send-mail@v3
         with:
           server_address: smtp.office365.com
           server_port: 587
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
-          subject: 'Build Failed: Chatbot Client'
-          body: 'The build for Chatbot Client failed in the GitHub Action workflow.'
+          subject: 'Build Failed: build2'
+          body: 'The build for build2 failed in the GitHub Action workflow.'
           to: 'haritha.guduru@gytworkz.com'
-          from: 'santosh.chintapally@gytworkz.com'   
+          from: 'santosh.chintapally@gytworkz.com'
